--- #YAML:1.0
name:                   CPAN-YACSmoke-Plugin-NNTPWeb
version:                0.05
abstract:               NNTP web plugin for CPAN-YACSmoke
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  CPAN::YACSmoke:       0.03
  Template::Extract:    0
  WWW::Mechanize:       0
  Storable:             0
  File::Basename:       0
  File::Path:           0
  Test::More:           0.47
recommends:
  Test::More:           0.47
  Test::Pod:            1.00
  Test::Pod::Coverage:  0.08
  Test::YAML::Meta:     0.03
build_requires:
  Test::More:           0.47

provides:
  CPAN::YACSmoke::Plugin::NNTPWeb:
    file:     lib/CPAN/YACSmoke/Plugin/NNTPWeb.pm
    version:  0.05
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
